version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: healthy-food-api
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  db:
    image: mariadb:10.6              # gunakan versi yang stabil
    container_name: healthy-food-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthy_foods   # nama DB harus sama dengan di init.sql
      MYSQL_USER: user                # optional
      MYSQL_PASSWORD: root    # optional
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"                   # boleh dipakai untuk debug
    deploy:
      resources:
        limits:
          memory: 256M
